const now = new Date();
const day = 24 * 60 * 60 * 1000;

const objectId = (suffix: string) => `000000000000000000000${suffix}`.slice(-24);
const isoDaysFromNow = (offset: number) => new Date(now.getTime() + offset * day).toISOString();
const isoDaysAgo = (offset: number) => new Date(now.getTime() - offset * day).toISOString();

export const sampleCustomers = [
  {
    _id: objectId('101'),
    email: 'nimal.perera@example.com',
    name: 'Nimal Perera',
    phone: '+94 77 123 4567',
    address: '12 Lake Road',
    city: 'Colombo',
    country: 'Sri Lanka',
    totalBookings: 4,
    totalSpent: 185000,
    isVIP: true,
    preferences: {
      roomCategory: 'Suite',
      specialRequests: 'Late check-in and airport pickup',
    },
    createdAt: isoDaysAgo(120),
    updatedAt: isoDaysAgo(5),
  },
  {
    _id: objectId('102'),
    email: 'sara.jay@example.com',
    name: 'Sara Jayasinghe',
    phone: '+94 71 888 2211',
    address: '45 Galle Face',
    city: 'Colombo',
    country: 'Sri Lanka',
    totalBookings: 2,
    totalSpent: 92000,
    isVIP: false,
    preferences: {
      roomCategory: 'Deluxe',
      specialRequests: 'Vegetarian meals',
    },
    createdAt: isoDaysAgo(75),
    updatedAt: isoDaysAgo(12),
  },
  {
    _id: objectId('103'),
    email: 'travel.group@example.com',
    name: 'Island Explorers Pvt Ltd',
    phone: '+94 76 555 9012',
    address: '88 Marine Drive',
    city: 'Negombo',
    country: 'Sri Lanka',
    totalBookings: 6,
    totalSpent: 310000,
    isVIP: true,
    preferences: {
      roomCategory: 'Standard',
      specialRequests: 'Group transport coordination',
    },
    createdAt: isoDaysAgo(160),
    updatedAt: isoDaysAgo(3),
  },
];

export const sampleRooms = [
  {
    _id: objectId('201'),
    roomNumber: '101',
    category: 'Standard',
    capacity: 2,
    pricePerNight: 18000,
    description: 'Comfortable garden-facing room with queen bed.',
    amenities: ['WiFi', 'Air Conditioning', 'Tea/Coffee Maker'],
    images: ['/rooms/101-1.jpg'],
    isAvailable: true,
    createdAt: isoDaysAgo(200),
    updatedAt: isoDaysAgo(4),
  },
  {
    _id: objectId('202'),
    roomNumber: '204',
    category: 'Deluxe',
    capacity: 3,
    pricePerNight: 28500,
    description: 'Sea-view deluxe room with balcony seating.',
    amenities: ['WiFi', 'Balcony', 'Mini Bar', 'Smart TV'],
    images: ['/rooms/204-1.jpg'],
    isAvailable: false,
    createdAt: isoDaysAgo(180),
    updatedAt: isoDaysAgo(1),
  },
  {
    _id: objectId('203'),
    roomNumber: '305',
    category: 'Suite',
    capacity: 4,
    pricePerNight: 42000,
    description: 'Spacious suite with living area and lagoon view.',
    amenities: ['WiFi', 'Jacuzzi', 'Living Area', 'Butler Service'],
    images: ['/rooms/305-1.jpg'],
    isAvailable: true,
    createdAt: isoDaysAgo(140),
    updatedAt: isoDaysAgo(7),
  },
  {
    _id: objectId('204'),
    roomNumber: '401',
    category: 'Presidential',
    capacity: 6,
    pricePerNight: 95000,
    description: 'Premium presidential suite with private terrace.',
    amenities: ['Private Terrace', 'Jacuzzi', 'Dining Area', 'Ocean View'],
    images: ['/rooms/401-1.jpg'],
    isAvailable: true,
    createdAt: isoDaysAgo(110),
    updatedAt: isoDaysAgo(9),
  },
];

export const sampleBookings = [
  {
    _id: objectId('301'),
    bookingId: 'BK-SAMPLE-001',
    customerId: sampleCustomers[0]._id,
    customerName: sampleCustomers[0].name,
    customerEmail: sampleCustomers[0].email,
    customerPhone: sampleCustomers[0].phone,
    roomIds: [sampleRooms[1]._id],
    checkInDate: isoDaysAgo(1),
    checkOutDate: isoDaysFromNow(2),
    numberOfNights: 3,
    numberOfGuests: 2,
    totalAmount: 85500,
    promoCode: 'WELCOME10',
    discountAmount: 9500,
    amountPaid: 40000,
    payments: [
      {
        _id: objectId('901'),
        amount: 40000,
        method: 'card',
        date: isoDaysAgo(2),
        notes: 'Advance payment',
        recordedBy: 'Front Desk',
      },
    ],
    status: 'checked-in',
    paymentStatus: 'partial',
    paymentMethod: 'card',
    notes: 'Airport pickup requested.',
    bookingFromSource: 'direct',
    externalBookingId: '',
    checkInTime: isoDaysAgo(1),
    createdAt: isoDaysAgo(8),
    updatedAt: isoDaysAgo(1),
  },
  {
    _id: objectId('302'),
    bookingId: 'BK-SAMPLE-002',
    customerId: sampleCustomers[1]._id,
    customerName: sampleCustomers[1].name,
    customerEmail: sampleCustomers[1].email,
    customerPhone: sampleCustomers[1].phone,
    roomIds: [sampleRooms[0]._id, sampleRooms[2]._id],
    checkInDate: isoDaysFromNow(5),
    checkOutDate: isoDaysFromNow(8),
    numberOfNights: 3,
    numberOfGuests: 4,
    totalAmount: 180000,
    discountAmount: 0,
    amountPaid: 180000,
    payments: [
      {
        _id: objectId('902'),
        amount: 180000,
        method: 'bank_transfer',
        date: isoDaysAgo(1),
        notes: 'Full advance',
        recordedBy: 'Reservations',
      },
    ],
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    notes: 'Family suite arrangement requested.',
    bookingFromSource: 'booking.com',
    externalBookingId: 'BDC-44882',
    createdAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
  },
  {
    _id: objectId('303'),
    bookingId: 'BK-SAMPLE-003',
    customerId: sampleCustomers[2]._id,
    customerName: sampleCustomers[2].name,
    customerEmail: sampleCustomers[2].email,
    customerPhone: sampleCustomers[2].phone,
    roomIds: [sampleRooms[3]._id],
    checkInDate: isoDaysFromNow(12),
    checkOutDate: isoDaysFromNow(14),
    numberOfNights: 2,
    numberOfGuests: 5,
    totalAmount: 190000,
    discountAmount: 0,
    amountPaid: 0,
    payments: [],
    status: 'pending',
    paymentStatus: 'unpaid',
    paymentMethod: '',
    notes: 'Corporate retreat hold.',
    bookingFromSource: 'other',
    externalBookingId: 'AGENT-991',
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleMenuItems = [
  {
    _id: objectId('401'),
    name: 'Coconut Prawn Curry',
    description: 'King prawns simmered in coconut gravy.',
    category: 'main',
    price: 3200,
    vegetarian: false,
    spiceLevel: 3,
    available: true,
    image: '/menu/prawn-curry.jpg',
    preparationTime: 25,
    createdAt: isoDaysAgo(40),
  },
  {
    _id: objectId('402'),
    name: 'Tropical Fruit Platter',
    description: 'Seasonal fruits with passionfruit drizzle.',
    category: 'dessert',
    price: 1400,
    vegetarian: true,
    spiceLevel: 0,
    available: true,
    image: '/menu/fruit-platter.jpg',
    preparationTime: 10,
    createdAt: isoDaysAgo(35),
  },
  {
    _id: objectId('403'),
    name: 'Lemongrass Iced Tea',
    description: 'Fresh brewed iced tea infused with lemongrass.',
    category: 'beverage',
    price: 850,
    vegetarian: true,
    spiceLevel: 0,
    available: true,
    image: '/menu/iced-tea.jpg',
    preparationTime: 5,
    createdAt: isoDaysAgo(28),
  },
  {
    _id: objectId('404'),
    name: 'Chef Seafood Platter',
    description: 'Weekend special with grilled catch and shellfish.',
    category: 'special',
    price: 5600,
    vegetarian: false,
    spiceLevel: 2,
    available: false,
    image: '/menu/seafood-platter.jpg',
    preparationTime: 35,
    createdAt: isoDaysAgo(14),
  },
];

export const sampleRestaurantTables = [
  {
    _id: objectId('451'),
    tableNumber: 'T1',
    capacity: 2,
    location: 'indoor',
    status: 'available',
    amenities: ['window_view'],
    createdAt: isoDaysAgo(60),
  },
  {
    _id: objectId('452'),
    tableNumber: 'T5',
    capacity: 6,
    location: 'outdoor',
    status: 'reserved',
    amenities: ['garden_view', 'umbrella_shade'],
    createdAt: isoDaysAgo(54),
  },
  {
    _id: objectId('453'),
    tableNumber: 'P2',
    capacity: 10,
    location: 'private',
    status: 'occupied',
    amenities: ['private_corner', 'birthday_setup'],
    createdAt: isoDaysAgo(50),
  },
];

export const sampleRestaurantReservations = [
  {
    _id: objectId('461'),
    customerId: sampleCustomers[0]._id,
    tableId: sampleRestaurantTables[1]._id,
    reservationDate: isoDaysFromNow(1),
    guestCount: 5,
    duration: 120,
    specialRequests: 'Anniversary cake presentation',
    status: 'confirmed',
    contactPhone: sampleCustomers[0].phone,
    notes: 'Seafood-free menu',
    createdAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(1),
  },
  {
    _id: objectId('462'),
    customerId: sampleCustomers[1]._id,
    tableId: sampleRestaurantTables[0]._id,
    reservationDate: isoDaysFromNow(3),
    guestCount: 2,
    duration: 90,
    specialRequests: 'High chair not required',
    status: 'pending',
    contactPhone: sampleCustomers[1].phone,
    notes: '',
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleRestaurantOrders = [
  {
    _id: objectId('471'),
    reservationId: sampleRestaurantReservations[0]._id,
    customerId: sampleCustomers[0]._id,
    orderType: 'dine-in',
    mealType: 'dinner',
    roomNumber: '',
    items: [
      {
        menuItemId: sampleMenuItems[0]._id,
        itemName: sampleMenuItems[0].name,
        quantity: 2,
        specialInstructions: 'Medium spice',
        price: 3200,
      },
      {
        menuItemId: sampleMenuItems[2]._id,
        itemName: sampleMenuItems[2].name,
        quantity: 3,
        specialInstructions: '',
        price: 850,
      },
    ],
    subtotal: 8950,
    tax: 1074,
    discount: 500,
    total: 9524,
    paymentStatus: 'partial',
    paymentMethod: 'card',
    status: 'preparing',
    orderTime: isoDaysAgo(0),
    createdAt: isoDaysAgo(0),
    updatedAt: isoDaysAgo(0),
  },
  {
    _id: objectId('472'),
    bookingId: sampleBookings[0]._id,
    customerId: sampleCustomers[0]._id,
    orderType: 'room-service',
    mealType: 'breakfast',
    roomNumber: '204',
    items: [
      {
        menuItemId: sampleMenuItems[1]._id,
        itemName: sampleMenuItems[1].name,
        quantity: 1,
        specialInstructions: 'No honey',
        price: 1400,
      },
    ],
    subtotal: 1400,
    tax: 168,
    discount: 0,
    total: 1568,
    paymentStatus: 'charged_to_room',
    paymentMethod: 'room_charge',
    status: 'delivered',
    orderTime: isoDaysAgo(1),
    completionTime: isoDaysAgo(1),
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleDayOutPackages = [
  {
    _id: objectId('501'),
    name: 'Lagoon Adventure Day',
    description: 'A full day with kayaking, lunch, and beach games.',
    price: 45000,
    capacity: 40,
    duration: 8,
    activities: ['Kayaking', 'Beach Volleyball', 'Swimming'],
    inclusions: ['Welcome drink', 'Buffet lunch', 'Locker access'],
    image: '/dayout/lagoon-adventure.jpg',
    minGroupSize: 10,
    maxGroupSize: 40,
    availability: {
      startDate: isoDaysAgo(30),
      endDate: isoDaysFromNow(120),
      daysOfWeek: [1, 3, 5, 6],
    },
    amenities: ['Changing rooms', 'Parking', 'First-aid'],
    pricePerPerson: 4500,
    discountPercentage: 10,
    createdAt: isoDaysAgo(50),
  },
  {
    _id: objectId('502'),
    name: 'Corporate Chill Escape',
    description: 'Team-building package with conference setup and BBQ dinner.',
    price: 98000,
    capacity: 80,
    duration: 10,
    activities: ['Team games', 'Pool access', 'Live music'],
    inclusions: ['Conference hall', 'Snacks', 'BBQ dinner'],
    image: '/dayout/corporate-escape.jpg',
    minGroupSize: 25,
    maxGroupSize: 80,
    availability: {
      startDate: isoDaysAgo(15),
      endDate: isoDaysFromNow(150),
      daysOfWeek: [2, 4, 6],
    },
    amenities: ['Projector', 'Sound system', 'WiFi'],
    pricePerPerson: 4900,
    discountPercentage: 5,
    createdAt: isoDaysAgo(42),
  },
];

export const sampleGroupBookings = [
  {
    _id: objectId('511'),
    packageId: sampleDayOutPackages[0]._id,
    customerId: sampleCustomers[2]._id,
    groupName: 'Island Explorers Team Outing',
    bookingDate: isoDaysFromNow(10),
    numberOfPeople: 22,
    totalPrice: 89100,
    depositAmount: 26730,
    balanceAmount: 62370,
    paymentStatus: 'partial',
    status: 'confirmed',
    specialRequests: 'Vegetarian lunch for 6 guests',
    contactPerson: {
      name: 'Ravindu Silva',
      phone: '+94 77 321 8899',
      email: 'ravindu@islandexplorers.lk',
    },
    activities: ['Kayaking', 'Beach Volleyball'],
    notes: 'Bus arrival at 8:30 AM',
    createdAt: isoDaysAgo(4),
    updatedAt: isoDaysAgo(2),
  },
];

export const sampleBoatRidePackages = [
  {
    _id: objectId('521'),
    name: 'Sunset Speed Boat Tour',
    description: 'Fast-paced sunset lagoon ride with refreshments.',
    boatType: 'speed_boat',
    capacity: 8,
    price: 24000,
    pricePerPerson: 3200,
    duration: 90,
    routeDescription: 'Lagoon to mangrove belt and back to marina.',
    landmarks: ['Dutch Canal', 'Mangrove Point', 'Lighthouse View'],
    mealIncluded: false,
    lifeJacketsProvided: true,
    availability: {
      startDate: isoDaysAgo(10),
      endDate: isoDaysFromNow(90),
      departureTime: ['16:30', '17:30'],
    },
    safetyRating: 5,
    createdAt: isoDaysAgo(20),
  },
  {
    _id: objectId('522'),
    name: 'Houseboat Dinner Cruise',
    description: 'Relaxed evening cruise with seafood dinner and music.',
    boatType: 'houseboat',
    capacity: 20,
    price: 78000,
    pricePerPerson: 4500,
    duration: 180,
    routeDescription: 'Evening canal cruise with dinner stopover.',
    landmarks: ['Canal Bridge', 'Bird Island', 'Harbor Lights'],
    mealIncluded: true,
    lifeJacketsProvided: true,
    availability: {
      startDate: isoDaysAgo(5),
      endDate: isoDaysFromNow(120),
      departureTime: ['18:00'],
    },
    safetyRating: 4,
    createdAt: isoDaysAgo(18),
  },
];

export const sampleBoatRideBookings = [
  {
    _id: objectId('531'),
    packageId: sampleBoatRidePackages[0]._id,
    customerId: sampleCustomers[1]._id,
    bookingDate: isoDaysFromNow(4),
    departureTime: '17:30',
    numberOfPassengers: 4,
    totalPrice: 12800,
    paymentStatus: 'paid',
    status: 'confirmed',
    specialRequests: 'Window-side seating preference',
    notes: 'Birthday surprise setup',
    createdAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleSuppliers = [
  {
    _id: objectId('601'),
    name: 'Ocean Fresh Supplies',
    contactPerson: 'Mahesh Fernando',
    email: 'orders@oceanfresh.lk',
    phone: '+94 31 456 7788',
    address: '22 Fish Market Road',
    city: 'Negombo',
    state: 'Western',
    zipCode: '11500',
    paymentTerms: '30 days',
    taxId: 'VAT-NEG-001',
    rating: 4.8,
    isActive: true,
    createdAt: isoDaysAgo(180),
    updatedAt: isoDaysAgo(10),
  },
  {
    _id: objectId('602'),
    name: 'Green Harvest Traders',
    contactPerson: 'Dilini Peris',
    email: 'hello@greenharvest.lk',
    phone: '+94 11 889 7766',
    address: '104 Market Street',
    city: 'Colombo',
    state: 'Western',
    zipCode: '00100',
    paymentTerms: '15 days',
    taxId: 'VAT-CMB-112',
    rating: 4.5,
    isActive: true,
    createdAt: isoDaysAgo(150),
    updatedAt: isoDaysAgo(7),
  },
];

export const sampleInventoryItems = [
  {
    _id: objectId('611'),
    name: 'Tiger Prawns',
    category: 'food',
    quantity: 18,
    unit: 'kg',
    minimumLevel: 10,
    maximumLevel: 40,
    unitCost: 3200,
    supplier: sampleSuppliers[0]._id,
    location: 'Freezer A',
    expiryDate: isoDaysFromNow(6),
    lastRestocked: isoDaysAgo(2),
    createdAt: isoDaysAgo(60),
    updatedAt: isoDaysAgo(2),
  },
  {
    _id: objectId('612'),
    name: 'Fresh Lime',
    category: 'beverage',
    quantity: 120,
    unit: 'pcs',
    minimumLevel: 40,
    maximumLevel: 200,
    unitCost: 45,
    supplier: sampleSuppliers[1]._id,
    location: 'Bar Store',
    expiryDate: isoDaysFromNow(4),
    lastRestocked: isoDaysAgo(1),
    createdAt: isoDaysAgo(45),
    updatedAt: isoDaysAgo(1),
  },
  {
    _id: objectId('613'),
    name: 'Guest Towels',
    category: 'supplies',
    quantity: 240,
    unit: 'pcs',
    minimumLevel: 100,
    maximumLevel: 400,
    unitCost: 850,
    supplier: sampleSuppliers[1]._id,
    location: 'Laundry Store',
    lastRestocked: isoDaysAgo(8),
    createdAt: isoDaysAgo(80),
    updatedAt: isoDaysAgo(8),
  },
];

export const sampleInventoryTransactions = [
  {
    _id: objectId('621'),
    itemId: sampleInventoryItems[0]._id,
    type: 'stock_in',
    quantity: 10,
    previousQuantity: 8,
    newQuantity: 18,
    reason: 'Weekly seafood delivery',
    reference: 'GRN-1001',
    performedBy: objectId('701'),
    createdAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(2),
  },
  {
    _id: objectId('622'),
    itemId: sampleInventoryItems[1]._id,
    type: 'stock_out',
    quantity: 35,
    previousQuantity: 155,
    newQuantity: 120,
    reason: 'Restaurant consumption',
    reference: 'KOT-430',
    performedBy: objectId('702'),
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleEmployees = [
  {
    _id: objectId('701'),
    name: 'Ayesha Fernando',
    email: 'ayesha@lexienthotel.com',
    phone: '+94 77 555 1001',
    department: 'management',
    position: 'Operations Manager',
    joiningDate: isoDaysAgo(560),
    salary: 185000,
    employmentType: 'full-time',
    status: 'active',
    address: '28 Lake Crescent, Colombo 07',
    emergencyContact: {
      name: 'Nuwan Fernando',
      phone: '+94 77 555 3001',
      relation: 'Spouse',
    },
    bankDetails: {
      accountHolder: 'Ayesha Fernando',
      accountNumber: '1122334455',
      bankName: 'Commercial Bank',
      ifscCode: 'COMB001',
    },
    documents: {
      aadhar: '',
      pan: '',
      drivingLicense: 'B4455667',
    },
    createdAt: isoDaysAgo(560),
    updatedAt: isoDaysAgo(9),
  },
  {
    _id: objectId('702'),
    name: 'Ruwan Perera',
    email: 'ruwan@lexienthotel.com',
    phone: '+94 71 222 4488',
    department: 'restaurant',
    position: 'Restaurant Supervisor',
    joiningDate: isoDaysAgo(320),
    salary: 95000,
    employmentType: 'full-time',
    status: 'active',
    address: '44 Temple Road, Negombo',
    emergencyContact: {
      name: 'Malsha Perera',
      phone: '+94 71 222 5577',
      relation: 'Sister',
    },
    bankDetails: {
      accountHolder: 'Ruwan Perera',
      accountNumber: '2233445566',
      bankName: 'Sampath Bank',
      ifscCode: 'SAMP002',
    },
    documents: {
      aadhar: '',
      pan: '',
      drivingLicense: 'C9988776',
    },
    createdAt: isoDaysAgo(320),
    updatedAt: isoDaysAgo(4),
  },
  {
    _id: objectId('703'),
    name: 'Chamari Silva',
    email: 'chamari@lexienthotel.com',
    phone: '+94 76 444 6611',
    department: 'front_desk',
    position: 'Front Desk Executive',
    joiningDate: isoDaysAgo(180),
    salary: 78000,
    employmentType: 'full-time',
    status: 'on_leave',
    address: '15 Beach Road, Ja-Ela',
    emergencyContact: {
      name: 'Sanjeewa Silva',
      phone: '+94 76 444 8899',
      relation: 'Brother',
    },
    bankDetails: {
      accountHolder: 'Chamari Silva',
      accountNumber: '3344556677',
      bankName: 'HNB',
      ifscCode: 'HNB003',
    },
    documents: {
      aadhar: '',
      pan: '',
      drivingLicense: '',
    },
    createdAt: isoDaysAgo(180),
    updatedAt: isoDaysAgo(2),
  },
];

export const sampleAttendance = [
  {
    _id: objectId('711'),
    employeeId: sampleEmployees[0]._id,
    attendanceDate: isoDaysAgo(0),
    checkInTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 45).toISOString(),
    checkOutTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 18, 5).toISOString(),
    status: 'present',
    remarks: 'Monthly review meetings',
    createdAt: isoDaysAgo(0),
  },
  {
    _id: objectId('712'),
    employeeId: sampleEmployees[1]._id,
    attendanceDate: isoDaysAgo(0),
    checkInTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 10).toISOString(),
    checkOutTime: undefined,
    status: 'present',
    remarks: 'Evening shift',
    createdAt: isoDaysAgo(0),
  },
  {
    _id: objectId('713'),
    employeeId: sampleEmployees[2]._id,
    attendanceDate: isoDaysAgo(0),
    checkInTime: undefined,
    checkOutTime: undefined,
    status: 'leave',
    remarks: 'Annual leave approved',
    createdAt: isoDaysAgo(0),
  },
];

export const samplePayrolls = [
  {
    _id: objectId('721'),
    employeeId: sampleEmployees[0]._id,
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`,
    basicSalary: 185000,
    allowances: 15000,
    deductions: 8500,
    netSalary: 191500,
    status: 'processed',
    paymentDate: isoDaysAgo(2),
    paymentMethod: 'bank_transfer',
    remarks: 'Includes performance bonus',
    createdAt: isoDaysAgo(4),
  },
  {
    _id: objectId('722'),
    employeeId: sampleEmployees[1]._id,
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`,
    basicSalary: 95000,
    allowances: 5000,
    deductions: 2500,
    netSalary: 97500,
    status: 'pending',
    createdAt: isoDaysAgo(4),
  },
];

export const sampleIncome = [
  {
    _id: objectId('801'),
    source: 'booking',
    reference: sampleBookings[1].bookingId,
    amount: 180000,
    paymentMethod: 'online',
    description: 'Advance payment for family stay booking',
    notes: 'Collected via payment gateway',
    recordedBy: sampleEmployees[0]._id,
    recordedDate: isoDaysAgo(1),
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
  {
    _id: objectId('802'),
    source: 'restaurant',
    reference: 'REST-472',
    amount: 9524,
    paymentMethod: 'card',
    description: 'Dinner service revenue',
    notes: 'Anniversary dining reservation',
    recordedBy: sampleEmployees[1]._id,
    recordedDate: isoDaysAgo(0),
    createdAt: isoDaysAgo(0),
    updatedAt: isoDaysAgo(0),
  },
  {
    _id: objectId('803'),
    source: 'wedding_hall',
    reference: 'WE-001',
    amount: 150000,
    paymentMethod: 'check',
    description: 'Advance payment for wedding hall booking',
    notes: '',
    recordedBy: sampleEmployees[0]._id,
    recordedDate: isoDaysAgo(5),
    createdAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(5),
  },
];

export const sampleExpenses = [
  {
    _id: objectId('811'),
    category: 'food',
    description: 'Seafood and produce purchase',
    amount: 48500,
    paymentMethod: 'bank_transfer',
    vendor: sampleSuppliers[0].name,
    invoice: 'INV-FOOD-101',
    notes: 'Weekend procurement',
    attachments: [],
    approvedBy: sampleEmployees[0]._id,
    status: 'paid',
    dueDate: isoDaysAgo(3),
    paidDate: isoDaysAgo(2),
    createdBy: sampleEmployees[0]._id,
    createdAt: isoDaysAgo(4),
    updatedAt: isoDaysAgo(2),
  },
  {
    _id: objectId('812'),
    category: 'utilities',
    description: 'Electricity bill for main property',
    amount: 72000,
    paymentMethod: 'card',
    vendor: 'CEB',
    invoice: 'UTIL-APR-22',
    notes: 'Due before month end',
    attachments: [],
    status: 'approved',
    dueDate: isoDaysFromNow(2),
    createdBy: sampleEmployees[0]._id,
    createdAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleWeddingHalls = [
  {
    _id: objectId('901'),
    name: 'Grand Pearl Ballroom',
    capacity: 350,
    area: 5200,
    basePrice: 275000,
    amenities: ['Stage', 'LED Wall', 'Bridal Suite', 'Valet Parking'],
    images: ['/wedding/grand-pearl.jpg'],
    description: 'Elegant ballroom for large weddings and receptions.',
    availability: 'available',
    createdAt: isoDaysAgo(220),
    updatedAt: isoDaysAgo(6),
  },
  {
    _id: objectId('902'),
    name: 'Lagoon Garden Pavilion',
    capacity: 180,
    area: 3400,
    basePrice: 165000,
    amenities: ['Garden Arch', 'Outdoor Lighting', 'Dance Floor'],
    images: ['/wedding/lagoon-garden.jpg'],
    description: 'Open-air pavilion ideal for intimate celebrations.',
    availability: 'booked',
    createdAt: isoDaysAgo(200),
    updatedAt: isoDaysAgo(2),
  },
];

export const sampleWeddingEvents = [
  {
    _id: objectId('911'),
    hallId: sampleWeddingHalls[1]._id,
    clientName: 'Tharushi & Kavin',
    clientEmail: 'tharushi.kavin@example.com',
    clientPhone: '+94 77 777 1212',
    eventDate: isoDaysFromNow(18),
    eventType: 'wedding',
    expectedGuests: 160,
    totalPrice: 235000,
    advancePayment: 100000,
    remainingPayment: 135000,
    status: 'confirmed',
    notes: 'Floral pastel theme',
    requirements: ['Live band', 'Vegetarian buffet corner'],
    contactPerson: 'Mrs. Sandya Perera',
    createdAt: isoDaysAgo(12),
    updatedAt: isoDaysAgo(3),
  },
  {
    _id: objectId('912'),
    hallId: sampleWeddingHalls[0]._id,
    clientName: 'Nethmi Events',
    clientEmail: 'coordination@nethmievents.lk',
    clientPhone: '+94 11 456 9900',
    eventDate: isoDaysFromNow(32),
    eventType: 'reception',
    expectedGuests: 280,
    totalPrice: 320000,
    advancePayment: 50000,
    remainingPayment: 270000,
    status: 'inquiry',
    notes: 'Client evaluating menu options',
    requirements: ['Photo booth', 'Custom dessert station'],
    contactPerson: 'Nethmi Peris',
    createdAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(1),
  },
];

export const sampleAnalyticsMetrics = [
  {
    _id: objectId('951'),
    date: isoDaysAgo(0),
    metric: 'occupancy_rate',
    value: 78,
    breakdown: {
      byRoom: { Standard: 82, Deluxe: 75, Suite: 70, Presidential: 50 },
      byService: { hotel: 78 },
    },
    createdAt: isoDaysAgo(0),
    updatedAt: isoDaysAgo(0),
  },
  {
    _id: objectId('952'),
    date: isoDaysAgo(0),
    metric: 'total_revenue',
    value: 339524,
    breakdown: {
      byService: { bookings: 180000, restaurant: 9524, wedding: 150000 },
      byPaymentMethod: { card: 9524, online: 180000, check: 150000 },
    },
    createdAt: isoDaysAgo(0),
    updatedAt: isoDaysAgo(0),
  },
  {
    _id: objectId('953'),
    date: isoDaysAgo(0),
    metric: 'total_bookings',
    value: 3,
    breakdown: {
      byRoom: { Standard: 1, Deluxe: 1, Suite: 1 },
      byCustomerSegment: { vip: 2, regular: 1 },
    },
    createdAt: isoDaysAgo(0),
    updatedAt: isoDaysAgo(0),
  },
];

export const sampleReports = [
  {
    _id: objectId('961'),
    title: 'Monthly Revenue Snapshot',
    type: 'revenue',
    period: 'monthly',
    startDate: isoDaysAgo(30),
    endDate: isoDaysAgo(0),
    generatedBy: sampleEmployees[0]._id,
    data: {
      roomRevenue: 180000,
      restaurantRevenue: 9524,
      weddingRevenue: 150000,
    },
    summary: {
      totalRevenue: 339524,
      totalBookings: 3,
      averageOccupancy: 78,
      averageBookingValue: 113175,
      customerSatisfaction: 4.6,
    },
    charts: [
      {
        type: 'bar',
        title: 'Revenue by Department',
        data: [
          { label: 'Rooms', value: 180000 },
          { label: 'Restaurant', value: 9524 },
          { label: 'Wedding', value: 150000 },
        ],
      },
    ],
    filePath: '/reports/monthly-revenue-snapshot.pdf',
    shared: [],
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
];

export function withPopulatedRelations<T extends Record<string, any>>(items: T[], relations: Record<string, any>) {
  return items.map((item) => ({
    ...item,
    ...Object.fromEntries(
      Object.entries(relations)
        .filter(([key]) => key in item)
        .map(([key, collection]) => {
          const value = item[key];
          if (Array.isArray(value)) {
            return [key, value.map((id) => collection.find((entry: any) => entry._id === id) ?? id)];
          }
          return [key, collection.find((entry: any) => entry._id === value) ?? value];
        })
    ),
  }));
}
